export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  SCHOOL_SETTINGS_MANAGE: 'school.settings.manage',
  WEBSITE_OVERVIEW_MANAGE: 'website.overview.manage',
  WEBSITE_CUSTOM_PAGES_MANAGE: 'website.custom-pages.manage',
  WEBSITE_BANNERS_MANAGE: 'website.banners.manage',
  WEBSITE_HOME_MANAGE: 'website.home.manage',
  WEBSITE_ABOUT_MANAGE: 'website.about.manage',
  WEBSITE_ACADEMICS_MANAGE: 'website.academics.manage',
  WEBSITE_PROGRAMS_MANAGE: 'website.programs.manage',
  WEBSITE_GALLERY_MANAGE: 'website.gallery.manage',
  WEBSITE_EVENTS_MANAGE: 'website.events.manage',
  WEBSITE_ADMISSION_MANAGE: 'website.admission.manage',
  WEBSITE_TEACHERS_MANAGE: 'website.teachers.manage',
  WEBSITE_FACILITIES_MANAGE: 'website.facilities.manage',
  WEBSITE_ACHIEVEMENTS_MANAGE: 'website.achievements.manage',
  WEBSITE_DOWNLOADS_MANAGE: 'website.downloads.manage',
  WEBSITE_CONTACT_MANAGE: 'website.contact.manage',
  ACADEMIC_VIEW: 'academic.view',
  ACADEMIC_MANAGE: 'academic.manage',
  STUDENTS_VIEW: 'students.view',
  STUDENTS_MANAGE: 'students.manage',
  GUARDIANS_VIEW: 'guardians.view',
  GUARDIANS_MANAGE: 'guardians.manage',
  ADMISSIONS_VIEW: 'admissions.view',
  ADMISSIONS_MANAGE: 'admissions.manage',
  TEACHERS_VIEW: 'teachers.view',
  TEACHERS_MANAGE: 'teachers.manage',
  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_MANAGE: 'employees.manage',
  DEPARTMENTS_VIEW: 'departments.view',
  DEPARTMENTS_MANAGE: 'departments.manage',
  DESIGNATIONS_VIEW: 'designations.view',
  DESIGNATIONS_MANAGE: 'designations.manage',
  TEACHER_ASSIGNMENTS_VIEW: 'teacher-assignments.view',
  TEACHER_ASSIGNMENTS_MANAGE: 'teacher-assignments.manage',
  ROUTINES_VIEW: 'routines.view',
  ROUTINES_MANAGE: 'routines.manage',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  HOMEWORK_VIEW: 'homework.view',
  HOMEWORK_MANAGE: 'homework.manage',
  EXAMS_VIEW: 'exams.view',
  EXAMS_MANAGE: 'exams.manage',
  MARKS_ENTER: 'marks.enter',
  MARKS_VERIFY: 'marks.verify',
  MARKS_LOCK: 'marks.lock',
  RESULTS_CALCULATE: 'results.calculate',
  RESULTS_PUBLISH: 'results.publish',
  FEES_VIEW: 'fees.view',
  FEES_MANAGE: 'fees.manage',
  PAYMENTS_COLLECT: 'payments.collect',
  PAYMENTS_REVERSE: 'payments.reverse',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_GENERATE: 'payroll.generate',
  PAYROLL_APPROVE: 'payroll.approve',
  LEAVE_VIEW: 'leave.view',
  LEAVE_MANAGE: 'leave.manage',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  IMPORTS_VIEW: 'imports.view',
  IMPORTS_MANAGE: 'imports.manage',
  LEGACY_MIGRATE: 'legacy.migrate',
  TEACHER_PORTAL_VIEW: 'portal.teacher.view',
  STUDENT_PORTAL_VIEW: 'portal.student.view',
  GUARDIAN_PORTAL_VIEW: 'portal.guardian.view',
  EMPLOYEE_PORTAL_VIEW: 'portal.employee.view',
  AUDIT_VIEW: 'audit.view',
  BACKUP_MANAGE: 'backup.manage',
} as const;

export const WEBSITE_PERMISSIONS = [
  PERMISSIONS.WEBSITE_OVERVIEW_MANAGE,
  PERMISSIONS.WEBSITE_CUSTOM_PAGES_MANAGE,
  PERMISSIONS.WEBSITE_BANNERS_MANAGE,
  PERMISSIONS.WEBSITE_HOME_MANAGE,
  PERMISSIONS.WEBSITE_ABOUT_MANAGE,
  PERMISSIONS.WEBSITE_ACADEMICS_MANAGE,
  PERMISSIONS.WEBSITE_PROGRAMS_MANAGE,
  PERMISSIONS.WEBSITE_GALLERY_MANAGE,
  PERMISSIONS.WEBSITE_EVENTS_MANAGE,
  PERMISSIONS.WEBSITE_ADMISSION_MANAGE,
  PERMISSIONS.WEBSITE_TEACHERS_MANAGE,
  PERMISSIONS.WEBSITE_FACILITIES_MANAGE,
  PERMISSIONS.WEBSITE_ACHIEVEMENTS_MANAGE,
  PERMISSIONS.WEBSITE_DOWNLOADS_MANAGE,
  PERMISSIONS.WEBSITE_CONTACT_MANAGE,
] as const;

export const WEBSITE_SECTION_PERMISSIONS = {
  overview: PERMISSIONS.WEBSITE_OVERVIEW_MANAGE,
  'custom-pages': PERMISSIONS.WEBSITE_CUSTOM_PAGES_MANAGE,
  banners: PERMISSIONS.WEBSITE_BANNERS_MANAGE,
  home: PERMISSIONS.WEBSITE_HOME_MANAGE,
  about: PERMISSIONS.WEBSITE_ABOUT_MANAGE,
  'academic-activities': PERMISSIONS.WEBSITE_ACADEMICS_MANAGE,
  programs: PERMISSIONS.WEBSITE_PROGRAMS_MANAGE,
  gallery: PERMISSIONS.WEBSITE_GALLERY_MANAGE,
  events: PERMISSIONS.WEBSITE_EVENTS_MANAGE,
  'admission-information': PERMISSIONS.WEBSITE_ADMISSION_MANAGE,
  'our-teachers': PERMISSIONS.WEBSITE_TEACHERS_MANAGE,
  facilities: PERMISSIONS.WEBSITE_FACILITIES_MANAGE,
  achievements: PERMISSIONS.WEBSITE_ACHIEVEMENTS_MANAGE,
  downloads: PERMISSIONS.WEBSITE_DOWNLOADS_MANAGE,
  contact: PERMISSIONS.WEBSITE_CONTACT_MANAGE,
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'Super Admin',
  SCHOOL_ADMIN: 'School Admin',
  ACADEMIC_ADMIN: 'Academic Admin',
  ADMISSION_OFFICER: 'Admission Officer',
  ACCOUNTANT: 'Accountant',
  HR_MANAGER: 'HR Manager',
  TEACHER: 'Teacher',
  EMPLOYEE: 'Employee',
  STUDENT: 'Student',
  PARENT: 'Parent/Guardian',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];
