export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  SCHOOL_SETTINGS_MANAGE: 'school.settings.manage',
  ACADEMIC_VIEW: 'academic.view',
  ACADEMIC_MANAGE: 'academic.manage',
  STUDENTS_VIEW: 'students.view',
  STUDENTS_MANAGE: 'students.manage',
  ADMISSIONS_VIEW: 'admissions.view',
  ADMISSIONS_MANAGE: 'admissions.manage',
  TEACHERS_VIEW: 'teachers.view',
  TEACHERS_MANAGE: 'teachers.manage',
  ROUTINES_VIEW: 'routines.view',
  ROUTINES_MANAGE: 'routines.manage',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  EXAMS_VIEW: 'exams.view',
  EXAMS_MANAGE: 'exams.manage',
  MARKS_ENTER: 'marks.enter',
  MARKS_VERIFY: 'marks.verify',
  MARKS_LOCK: 'marks.lock',
  RESULTS_CALCULATE: 'results.calculate',
  RESULTS_PUBLISH: 'results.publish',
  FEES_VIEW: 'fees.view',
  FEES_MANAGE: 'fees.manage',
  PAYMENTS_COLLECT: 'payments.collect',
  PAYMENTS_REVERSE: 'payments.reverse',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_GENERATE: 'payroll.generate',
  PAYROLL_APPROVE: 'payroll.approve',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  AUDIT_VIEW: 'audit.view',
  BACKUP_MANAGE: 'backup.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'Super Admin',
  SCHOOL_ADMIN: 'School Admin',
  ACADEMIC_ADMIN: 'Academic Admin',
  ADMISSION_OFFICER: 'Admission Officer',
  ACCOUNTANT: 'Accountant',
  HR_MANAGER: 'HR Manager',
  TEACHER: 'Teacher',
  EMPLOYEE: 'Employee',
  STUDENT: 'Student',
  PARENT: 'Parent/Guardian',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];
