import React from 'react';

interface PrintLayoutProps {
  schoolName?: string;
  eiin?: string;
  address?: string;
  phone?: string;
  documentTitle: string;
  children: React.ReactNode;
}

export function PrintLayout({
  schoolName = 'School Management System',
  eiin = '',
  address = '',
  phone = '',
  documentTitle,
  children,
}: PrintLayoutProps) {
  return (
    <div className="bg-white p-8 max-w-4xl mx-auto border border-slate-200 rounded-xl print:border-none print:p-0 print:shadow-none">
      {/* Official Header */}
      <div className="text-center border-b border-slate-200 pb-4 mb-6">
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">{schoolName}</h1>
        {(eiin || address || phone) && <p className="text-xs font-semibold text-teal-700 mt-0.5">{[eiin && `EIIN: ${eiin}`, address, phone && `Tel: ${phone}`].filter(Boolean).join(' | ')}</p>}
        <div className="mt-3 inline-block px-4 py-1 bg-slate-100 rounded-full text-xs font-bold uppercase tracking-wider text-slate-800">
          {documentTitle}
        </div>
      </div>

      {/* Content */}
      <div className="space-y-4">{children}</div>

      {/* Footer */}
      <div className="mt-12 pt-4 border-t border-slate-200 flex items-center justify-between text-xs text-slate-400">
        <p>Generated by School Management System (Bangladesh)</p>
        <p>Authorized Signature: _______________________</p>
      </div>
    </div>
  );
}
